
package bankservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NasabahServiceService", targetNamespace = "http://BankService/", wsdlLocation = "http://localhost:8084/tesws?wsdl")
public class NasabahServiceService
    extends Service
{

    private final static URL NASABAHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException NASABAHSERVICESERVICE_EXCEPTION;
    private final static QName NASABAHSERVICESERVICE_QNAME = new QName("http://BankService/", "NasabahServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/tesws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NASABAHSERVICESERVICE_WSDL_LOCATION = url;
        NASABAHSERVICESERVICE_EXCEPTION = e;
    }

    public NasabahServiceService() {
        super(__getWsdlLocation(), NASABAHSERVICESERVICE_QNAME);
    }

    public NasabahServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NASABAHSERVICESERVICE_QNAME, features);
    }

    public NasabahServiceService(URL wsdlLocation) {
        super(wsdlLocation, NASABAHSERVICESERVICE_QNAME);
    }

    public NasabahServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NASABAHSERVICESERVICE_QNAME, features);
    }

    public NasabahServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NasabahServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NasabahService
     */
    @WebEndpoint(name = "NasabahServicePort")
    public NasabahService getNasabahServicePort() {
        return super.getPort(new QName("http://BankService/", "NasabahServicePort"), NasabahService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NasabahService
     */
    @WebEndpoint(name = "NasabahServicePort")
    public NasabahService getNasabahServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://BankService/", "NasabahServicePort"), NasabahService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NASABAHSERVICESERVICE_EXCEPTION!= null) {
            throw NASABAHSERVICESERVICE_EXCEPTION;
        }
        return NASABAHSERVICESERVICE_WSDL_LOCATION;
    }

}
